# Generated by Django 5.1.3 on 2024-12-10 18:44

import uuid
from django.db import migrations, models

def generate_unique_ids(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    for user in User.objects.all():
        user.unique_id = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(generate_unique_ids),
    ]
