# Generated by Django 5.1.3 on 2024-12-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_count', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'game_room',
            },
        ),
    ]
