# Generated by Django 5.1.3 on 2024-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
