# Generated by Django 5.1.3 on 2024-12-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameroom_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
